# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'doehlerDashboard.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import os
from SalesForecastUpdate import *
from SalesForecastUpdateEOM import *
from SendForecast import *
from LTODateFormatting import *
import datetime
import webbrowser

class Ui_Doehler_title(object):

    def sales_forecast_update_pushed(self):
        self.forecast_updater = QtWidgets.QMainWindow()
        self.ui = Ui_forecast_update_window()
        self.ui.setup_fc_update(self.forecast_updater)
        self.forecast_updater.show()

    def sales_forecast_EOM_pushed(self):
        self.forecast_EOM_updater = QtWidgets.QMainWindow()
        self.ui = Ui_forecast_EOM_window()
        self.ui.setup_fc_update(self.forecast_EOM_updater)
        self.forecast_EOM_updater.show()

    def local_fc_analysis_pushed(self):
        self.individual_forecast = QtWidgets.QMainWindow()
        self.ui = Ui_individual_forecast()
        self.ui.setupUi(self.individual_forecast)
        self.individual_forecast.show()

    def lto_date_convert_pushed(self):
        self.lto_date = QtWidgets.QMainWindow()
        self.ui = Ui_lto_date()
        self.ui.setupUi(self.lto_date)
        self.lto_date.show()


    def setupUi(self, Doehler_title):
        Doehler_title.setObjectName("Doehler_title")
        Doehler_title.setEnabled(True)
        Doehler_title.resize(1220, 645)
        Doehler_title.setMinimumSize(QtCore.QSize(1220, 645))
        Doehler_title.setMaximumSize(QtCore.QSize(1220, 645))
        Doehler_title.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(Doehler_title)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.app_title = QtWidgets.QLabel(self.centralwidget)
        self.app_title.setGeometry(QtCore.QRect(100, 0, 1121, 81))
        self.app_title.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(32)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.app_title.setFont(font)
        self.app_title.setStyleSheet("background-color: rgb(0, 35, 72);\n"
"color: rgb(255, 255, 255);")
        self.app_title.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.app_title.setFrameShadow(QtWidgets.QFrame.Plain)
        self.app_title.setMidLineWidth(0)
        self.app_title.setTextFormat(QtCore.Qt.PlainText)
        self.app_title.setAlignment(QtCore.Qt.AlignCenter)
        self.app_title.setWordWrap(False)
        self.app_title.setObjectName("app_title")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 101, 81))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Images/DoehlerLogo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.forecasting_box = QtWidgets.QGroupBox(self.centralwidget)
        self.forecasting_box.setGeometry(QtCore.QRect(10, 80, 361, 431))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.forecasting_box.setFont(font)
        self.forecasting_box.setObjectName("forecasting_box")
        self.sforecast_button = QtWidgets.QPushButton(self.forecasting_box)
        self.sforecast_button.setGeometry(QtCore.QRect(170, 40, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.sforecast_button.setFont(font)
        self.sforecast_button.setObjectName("sforecast_button")
        self.sforecast_eom_button = QtWidgets.QPushButton(self.forecasting_box)
        self.sforecast_eom_button.setGeometry(QtCore.QRect(170, 120, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.sforecast_eom_button.setFont(font)
        self.sforecast_eom_button.setObjectName("sforecast_eom_button")
        self.sforecast_visuals_button = QtWidgets.QPushButton(self.forecasting_box)
        self.sforecast_visuals_button.setGeometry(QtCore.QRect(170, 200, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.sforecast_visuals_button.setFont(font)
        self.sforecast_visuals_button.setObjectName("sforecast_visuals_button")
        self.bpm_forecast_button = QtWidgets.QPushButton(self.forecasting_box)
        self.bpm_forecast_button.setGeometry(QtCore.QRect(170, 280, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.bpm_forecast_button.setFont(font)
        self.bpm_forecast_button.setObjectName("bpm_forecast_button")
        self.bpm_visuals_button = QtWidgets.QPushButton(self.forecasting_box)
        self.bpm_visuals_button.setGeometry(QtCore.QRect(170, 360, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.bpm_visuals_button.setFont(font)
        self.bpm_visuals_button.setObjectName("bpm_visuals_button")
        self.forecast1_label = QtWidgets.QLabel(self.forecasting_box)
        self.forecast1_label.setEnabled(True)
        self.forecast1_label.setGeometry(QtCore.QRect(20, 60, 141, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.forecast1_label.sizePolicy().hasHeightForWidth())
        self.forecast1_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.forecast1_label.setFont(font)
        self.forecast1_label.setObjectName("forecast1_label")
        self.forecast2_label = QtWidgets.QLabel(self.forecasting_box)
        self.forecast2_label.setGeometry(QtCore.QRect(20, 140, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.forecast2_label.setFont(font)
        self.forecast2_label.setObjectName("forecast2_label")
        self.monthly_box = QtWidgets.QGroupBox(self.centralwidget)
        self.monthly_box.setGeometry(QtCore.QRect(420, 80, 371, 431))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.monthly_box.setFont(font)
        self.monthly_box.setObjectName("monthly_box")
        self.bwaging_button = QtWidgets.QPushButton(self.monthly_box)
        self.bwaging_button.setGeometry(QtCore.QRect(180, 40, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.bwaging_button.setFont(font)
        self.bwaging_button.setObjectName("bwaging_button")
        self.salesupload_button = QtWidgets.QPushButton(self.monthly_box)
        self.salesupload_button.setGeometry(QtCore.QRect(180, 120, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.salesupload_button.setFont(font)
        self.salesupload_button.setObjectName("salesupload_button")
        self.bcs_button = QtWidgets.QPushButton(self.monthly_box)
        self.bcs_button.setGeometry(QtCore.QRect(180, 200, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.bcs_button.setFont(font)
        self.bcs_button.setObjectName("bcs_button")
        self.ic_button = QtWidgets.QPushButton(self.monthly_box)
        self.ic_button.setGeometry(QtCore.QRect(180, 280, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.ic_button.setFont(font)
        self.ic_button.setObjectName("ic_button")
        self.bpc_button = QtWidgets.QPushButton(self.monthly_box)
        self.bpc_button.setGeometry(QtCore.QRect(180, 360, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.bpc_button.setFont(font)
        self.bpc_button.setObjectName("bpc_button")
        self.monthly1_label = QtWidgets.QLabel(self.monthly_box)
        self.monthly1_label.setGeometry(QtCore.QRect(20, 60, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.monthly1_label.setFont(font)
        self.monthly1_label.setObjectName("monthly1_label")
        self.monthly2_label = QtWidgets.QLabel(self.monthly_box)
        self.monthly2_label.setGeometry(QtCore.QRect(20, 140, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.monthly2_label.setFont(font)
        self.monthly2_label.setObjectName("monthly2_label")
        self.monthly4_label = QtWidgets.QLabel(self.monthly_box)
        self.monthly4_label.setGeometry(QtCore.QRect(20, 300, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.monthly4_label.setFont(font)
        self.monthly4_label.setObjectName("monthly4_label")
        self.monthly3_label = QtWidgets.QLabel(self.monthly_box)
        self.monthly3_label.setGeometry(QtCore.QRect(20, 220, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.monthly3_label.setFont(font)
        self.monthly3_label.setObjectName("monthly3_label")
        self.monthly5_label = QtWidgets.QLabel(self.monthly_box)
        self.monthly5_label.setGeometry(QtCore.QRect(20, 380, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.monthly5_label.setFont(font)
        self.monthly5_label.setObjectName("monthly5_label")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 510, 1201, 91))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton.setGeometry(QtCore.QRect(60, 40, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_5.setGeometry(QtCore.QRect(170, 40, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_6.setGeometry(QtCore.QRect(280, 40, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_7.setGeometry(QtCore.QRect(390, 40, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_8.setGeometry(QtCore.QRect(500, 40, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_9.setGeometry(QtCore.QRect(610, 40, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_10.setGeometry(QtCore.QRect(720, 40, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_11.setGeometry(QtCore.QRect(830, 40, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_12.setGeometry(QtCore.QRect(940, 40, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_13.setGeometry(QtCore.QRect(1050, 40, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setObjectName("pushButton_13")
        self.controlling_box = QtWidgets.QGroupBox(self.centralwidget)
        self.controlling_box.setGeometry(QtCore.QRect(840, 80, 371, 281))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.controlling_box.setFont(font)
        self.controlling_box.setObjectName("controlling_box")
        self.lto_button = QtWidgets.QPushButton(self.controlling_box)
        self.lto_button.setGeometry(QtCore.QRect(180, 40, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lto_button.setFont(font)
        self.lto_button.setObjectName("lto_button")
        self.legal_button = QtWidgets.QPushButton(self.controlling_box)
        self.legal_button.setGeometry(QtCore.QRect(180, 120, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.legal_button.setFont(font)
        self.legal_button.setObjectName("legal_button")
        self.bpm_analysis_button = QtWidgets.QPushButton(self.controlling_box)
        self.bpm_analysis_button.setGeometry(QtCore.QRect(180, 200, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.bpm_analysis_button.setFont(font)
        self.bpm_analysis_button.setObjectName("bpm_analysis_button")
        self.deadlines_box = QtWidgets.QGroupBox(self.centralwidget)
        self.deadlines_box.setGeometry(QtCore.QRect(840, 370, 371, 141))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.deadlines_box.setFont(font)
        self.deadlines_box.setObjectName("deadlines_box")
        self.deadline1_label = QtWidgets.QLabel(self.deadlines_box)
        self.deadline1_label.setGeometry(QtCore.QRect(20, 30, 341, 16))
        self.deadline1_label.setObjectName("deadline1_label")
        self.deadline2_label = QtWidgets.QLabel(self.deadlines_box)
        self.deadline2_label.setGeometry(QtCore.QRect(20, 50, 341, 16))
        self.deadline2_label.setObjectName("deadline2_label")
        self.deadline3_label = QtWidgets.QLabel(self.deadlines_box)
        self.deadline3_label.setGeometry(QtCore.QRect(20, 70, 341, 16))
        self.deadline3_label.setObjectName("deadline3_label")
        self.deadline4_label = QtWidgets.QLabel(self.deadlines_box)
        self.deadline4_label.setGeometry(QtCore.QRect(20, 90, 341, 16))
        self.deadline4_label.setObjectName("deadline4_label")
        self.deadline5_label = QtWidgets.QLabel(self.deadlines_box)
        self.deadline5_label.setGeometry(QtCore.QRect(20, 110, 341, 16))
        self.deadline5_label.setObjectName("deadline5_label")
        Doehler_title.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Doehler_title)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1220, 22))
        self.menubar.setObjectName("menubar")
        Doehler_title.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Doehler_title)
        self.statusbar.setObjectName("statusbar")
        Doehler_title.setStatusBar(self.statusbar)

        self.retranslateUi(Doehler_title)
        QtCore.QMetaObject.connectSlotsByName(Doehler_title)

        self.sforecast_button.clicked.connect(self.sales_forecast_update_pushed)
        self.sforecast_eom_button.clicked.connect(self.sales_forecast_EOM_pushed)
        self.legal_button.clicked.connect(self.local_fc_analysis_pushed)

        self.pushButton_13.clicked.connect(self.lto_date_convert_pushed)

        self.pushButton_5.clicked.connect(lambda: webbrowser.open("https://doehler.mytm5.com/system/portal.asp?url=%2FLMCash%2FKAmanValuten%2Easp&a_Meldung=AutoLogout&AG=1u&#e_Benutzer"))
        self.pushButton_6.clicked.connect(lambda: webbrowser.open("https://login.salesforce.com/"))
        self.pushButton_7.clicked.connect(lambda: webbrowser.open("https://cbportal.commerzbank.com/lp/login?fk&cifSecParams=SUxAAYR38N76HAQAKnx47VTw6hOzbzYbex3iUzOItBm4jsqr6GpZQg"))
        self.pushButton_8.clicked.connect(lambda: webbrowser.open("http://bpm.doehler.com.cn/Login.html"))
        self.pushButton_9.clicked.connect(lambda: webbrowser.open("https://portal.doehler.com/logon/LogonPoint/tmindex.html"))

    def retranslateUi(self, Doehler_title):
        _translate = QtCore.QCoreApplication.translate
        Doehler_title.setWindowTitle(_translate("Doehler_title", "Doehler Japan Portal, by Willem"))
        self.app_title.setText(_translate("Doehler_title", "Doehler Japan Dashboard"))
        self.forecasting_box.setTitle(_translate("Doehler_title", "Forecasting"))
        self.sforecast_button.setText(_translate("Doehler_title", "Sales Forecast Update"))
        self.sforecast_eom_button.setText(_translate("Doehler_title", "Sales Forecast EOM"))
        self.sforecast_visuals_button.setText(_translate("Doehler_title", "Sales Forecast Visuals"))
        self.bpm_forecast_button.setText(_translate("Doehler_title", "BPM Forecast"))
        self.bpm_visuals_button.setText(_translate("Doehler_title", "BPM Visuals"))
        self.forecast1_label.setText(_translate("Doehler_title", "MTD Sales <> Forecast"))
        self.forecast2_label.setText(_translate("Doehler_title", "After Sales Upload"))
        self.monthly_box.setTitle(_translate("Doehler_title", "Monthly Closing"))
        self.bwaging_button.setText(_translate("Doehler_title", "BW Aging List"))
        self.salesupload_button.setText(_translate("Doehler_title", "Sales Upload"))
        self.bcs_button.setText(_translate("Doehler_title", "BCS + Inventory"))
        self.ic_button.setText(_translate("Doehler_title", "IC Reconciliation"))
        self.bpc_button.setText(_translate("Doehler_title", "BPC"))

        # EOM Reporting schedule
        self.eom_deadlines()
        self.monthly1_label.setText(_translate("Doehler_title", self.deadline_days_text[1]))
        self.monthly2_label.setText(_translate("Doehler_title", self.deadline_days_text[1]))
        self.monthly3_label.setText(_translate("Doehler_title", self.deadline_days_text[2]))
        self.monthly4_label.setText(_translate("Doehler_title", self.deadline_days_text[0]))
        self.monthly5_label.setText(_translate("Doehler_title", self.deadline_days_text[4]))

        self.groupBox_3.setTitle(_translate("Doehler_title", "Extra Tools"))
        self.pushButton.setText(_translate("Doehler_title", "FX Calculator"))
        self.pushButton_5.setText(_translate("Doehler_title", "tm5 Login"))
        self.pushButton_6.setText(_translate("Doehler_title", "Salesforce"))
        self.pushButton_7.setText(_translate("Doehler_title", "Commerzbank"))
        self.pushButton_8.setText(_translate("Doehler_title", "BPM System"))
        self.pushButton_9.setText(_translate("Doehler_title", "Doehler Portal"))
        self.pushButton_10.setText(_translate("Doehler_title", "TBA"))
        self.pushButton_11.setText(_translate("Doehler_title", "TBA"))
        self.pushButton_12.setText(_translate("Doehler_title", "TBA"))
        self.pushButton_13.setText(_translate("Doehler_title", "LTO Date Format"))
        self.controlling_box.setTitle(_translate("Doehler_title", "Controlling"))
        self.lto_button.setText(_translate("Doehler_title", "LTO Analysis"))
        self.legal_button.setText(_translate("Doehler_title", "Local FC Analysis"))
        self.bpm_analysis_button.setText(_translate("Doehler_title", "BPM FC Analysis"))
        self.deadlines_box.setTitle(_translate("Doehler_title", "Fixed Deadlines"))
        self.deadline1_label.setText(_translate("Doehler_title", "Fixed Deadline 1"))
        self.deadline2_label.setText(_translate("Doehler_title", "Fixed Deadline 2"))
        self.deadline3_label.setText(_translate("Doehler_title", "Fixed Deadline 3"))
        self.deadline4_label.setText(_translate("Doehler_title", "Fixed Deadline 4"))
        self.deadline5_label.setText(_translate("Doehler_title", "Fixed Deadline 5"))


    def eom_deadlines(self):
        self.today = datetime.datetime.now()

        self.deadline_days = []
        if datetime.datetime.now().day > 9:
            self.deadline_day = datetime.datetime(self.today.year, self.today.month + 1, 1)
            while len(self.deadline_days) < 5:
                if self.deadline_day.weekday() in [5, 6]:
                    self.deadline_day = datetime.datetime(self.today.year, self.today.month + 1, self.deadline_day.day + 1)
                    continue
                else:
                    self.deadline_days.append(self.deadline_day.day)
                    self.deadline_day = datetime.datetime(self.today.year, self.today.month + 1, self.deadline_day.day + 1)
        else:
            self.deadline_day = datetime.datetime(self.today.year, self.today.month, 1)
            while len(self.deadline_days) < 5:
                if self.deadline_day.weekday() in [5, 6]:
                    self.deadline_day = datetime.datetime(self.today.year, self.today.month, self.deadline_day.day + 1)
                    continue
                else:
                    self.deadline_days.append(self.deadline_day.day)
                    self.deadline_day = datetime.datetime(self.today.year, self.today.month, self.deadline_day.day + 1)


        self.deadline_days_text = []
        for deadline in range(5):
            self.deadline_days_text.append(f"Next Deadline: {self.deadline_day.strftime('%Y/%m/')}{self.deadline_days[deadline]:02d}")

        # self.monthly1_label.setText(_translate("Doehler_title", self.deadline_days_text[0]))
        # self.monthly2_label.setText(_translate("Doehler_title", self.deadline_days_text[1]))
        # self.monthly3_label.setText(_translate("Doehler_title", self.deadline_days_text[2]))
        # self.monthly4_label.setText(_translate("Doehler_title", self.deadline_days_text[3]))
        # self.monthly5_label.setText(_translate("Doehler_title", self.deadline_days_text[4]))





if __name__ == "__main__":
    import sys
    os.environ["QT_AUTO_SCREEN_SCALE_FACTOR"] = "1"
    app = QtWidgets.QApplication(sys.argv)
    app.setStyle('Fusion')
    Doehler_title = QtWidgets.QMainWindow()
    ui = Ui_Doehler_title()
    ui.setupUi(Doehler_title)
    Doehler_title.show()
    sys.exit(app.exec_())
