# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SalesDashboardUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import os


class Ui_FCWindow(object):
    def setupUi(self, FCWindow):
        FCWindow.setObjectName("FCWindow")
        FCWindow.resize(1650, 967)
        FCWindow.setStyleSheet("background-color: rgb(0, 35, 72);")
        self.centralwidget = QtWidgets.QWidget(FCWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPixelSize(20)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("color: rgb(255, 255, 255);")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.summary_frame = QtWidgets.QFrame(self.tab)
        self.summary_frame.setGeometry(QtCore.QRect(0, 0, 1741, 905))
        self.summary_frame.setObjectName("summary_frame")
        self.jm_frame = QtWidgets.QFrame(self.summary_frame)
        self.jm_frame.setGeometry(QtCore.QRect(10, 170, 1611, 351))
        font = QtGui.QFont()
        font.setPixelSize(29)
        self.jm_frame.setFont(font)
        self.jm_frame.setStyleSheet("color: rgb(255, 255, 255);")
        self.jm_frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.jm_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.jm_frame.setLineWidth(10)
        self.jm_frame.setMidLineWidth(10)
        self.jm_frame.setObjectName("jm_frame")
        self.jm_chart = QtWidgets.QGridLayout(self.jm_frame)
        self.jm_chart.setGeometry(QtCore.QRect(10, 10, 1591, 331))
        self.jm_chart.setObjectName("jm_chart")
        self.kota_sum_frame = QtWidgets.QFrame(self.summary_frame)
        self.kota_sum_frame.setGeometry(QtCore.QRect(10, 30, 281, 131))
        font = QtGui.QFont()
        font.setPixelSize(29)
        self.kota_sum_frame.setFont(font)
        self.kota_sum_frame.setStyleSheet("color: rgb(255, 255, 255);")
        self.kota_sum_frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.kota_sum_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.kota_sum_frame.setLineWidth(10)
        self.kota_sum_frame.setMidLineWidth(10)
        self.kota_sum_frame.setObjectName("kota_sum_frame")
        self.kota_sum_label = QtWidgets.QLabel(self.kota_sum_frame)
        self.kota_sum_label.setGeometry(QtCore.QRect(10, 10, 161, 31))
        font = QtGui.QFont()
        font.setPixelSize(19)
        self.kota_sum_label.setFont(font)
        self.kota_sum_label.setObjectName("kota_sum_label")
        self.kota_sum_vol_label = QtWidgets.QLabel(self.kota_sum_frame)
        self.kota_sum_vol_label.setGeometry(QtCore.QRect(10, 50, 251, 21))
        font = QtGui.QFont()
        font.setPixelSize(15)
        self.kota_sum_vol_label.setFont(font)
        self.kota_sum_vol_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.kota_sum_vol_label.setLineWidth(1)
        self.kota_sum_vol_label.setObjectName("kota_sum_vol_label")
        self.kota_sum_ns_label = QtWidgets.QLabel(self.kota_sum_frame)
        self.kota_sum_ns_label.setGeometry(QtCore.QRect(10, 70, 251, 21))
        font = QtGui.QFont()
        font.setPixelSize(15)
        self.kota_sum_ns_label.setFont(font)
        self.kota_sum_ns_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.kota_sum_ns_label.setObjectName("kota_sum_ns_label")
        self.kota_sum_jm_label = QtWidgets.QLabel(self.kota_sum_frame)
        self.kota_sum_jm_label.setGeometry(QtCore.QRect(10, 90, 251, 21))
        font = QtGui.QFont()
        font.setPixelSize(15)
        self.kota_sum_jm_label.setFont(font)
        self.kota_sum_jm_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.kota_sum_jm_label.setObjectName("kota_sum_jm_label")
        self.hiyoshi_sum_frame = QtWidgets.QFrame(self.summary_frame)
        self.hiyoshi_sum_frame.setGeometry(QtCore.QRect(300, 30, 281, 131))
        font = QtGui.QFont()
        font.setPixelSize(29)
        self.hiyoshi_sum_frame.setFont(font)
        self.hiyoshi_sum_frame.setStyleSheet("color: rgb(255, 255, 255);")
        self.hiyoshi_sum_frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.hiyoshi_sum_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.hiyoshi_sum_frame.setLineWidth(10)
        self.hiyoshi_sum_frame.setMidLineWidth(10)
        self.hiyoshi_sum_frame.setObjectName("hiyoshi_sum_frame")
        self.hiyoshi_sum_label = QtWidgets.QLabel(self.hiyoshi_sum_frame)
        self.hiyoshi_sum_label.setGeometry(QtCore.QRect(10, 10, 161, 31))
        font = QtGui.QFont()
        font.setPixelSize(19)
        self.hiyoshi_sum_label.setFont(font)
        self.hiyoshi_sum_label.setObjectName("hiyoshi_sum_label")
        self.seiichi_sum_vol_label = QtWidgets.QLabel(self.hiyoshi_sum_frame)
        self.seiichi_sum_vol_label.setGeometry(QtCore.QRect(10, 50, 251, 21))
        font = QtGui.QFont()
        font.setPixelSize(15)
        self.seiichi_sum_vol_label.setFont(font)
        self.seiichi_sum_vol_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.seiichi_sum_vol_label.setLineWidth(1)
        self.seiichi_sum_vol_label.setObjectName("seiichi_sum_vol_label")
        self.seiichi_sum_ns_label = QtWidgets.QLabel(self.hiyoshi_sum_frame)
        self.seiichi_sum_ns_label.setGeometry(QtCore.QRect(10, 70, 251, 21))
        font = QtGui.QFont()
        font.setPixelSize(15)
        self.seiichi_sum_ns_label.setFont(font)
        self.seiichi_sum_ns_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.seiichi_sum_ns_label.setObjectName("seiichi_sum_ns_label")
        self.seiichi_sum_jm_label = QtWidgets.QLabel(self.hiyoshi_sum_frame)
        self.seiichi_sum_jm_label.setGeometry(QtCore.QRect(10, 90, 251, 21))
        font = QtGui.QFont()
        font.setPixelSize(15)
        self.seiichi_sum_jm_label.setFont(font)
        self.seiichi_sum_jm_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.seiichi_sum_jm_label.setObjectName("seiichi_sum_jm_label")
        self.takao_sum_frame = QtWidgets.QFrame(self.summary_frame)
        self.takao_sum_frame.setGeometry(QtCore.QRect(590, 30, 281, 131))
        font = QtGui.QFont()
        font.setPixelSize(29)
        self.takao_sum_frame.setFont(font)
        self.takao_sum_frame.setStyleSheet("color: rgb(255, 255, 255);")
        self.takao_sum_frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.takao_sum_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.takao_sum_frame.setLineWidth(10)
        self.takao_sum_frame.setMidLineWidth(10)
        self.takao_sum_frame.setObjectName("takao_sum_frame")
        self.takao_sum_label = QtWidgets.QLabel(self.takao_sum_frame)
        self.takao_sum_label.setGeometry(QtCore.QRect(10, 10, 161, 31))
        font = QtGui.QFont()
        font.setPixelSize(19)
        self.takao_sum_label.setFont(font)
        self.takao_sum_label.setObjectName("takao_sum_label")
        self.takao_sum_vol_label = QtWidgets.QLabel(self.takao_sum_frame)
        self.takao_sum_vol_label.setGeometry(QtCore.QRect(10, 50, 251, 21))
        font = QtGui.QFont()
        font.setPixelSize(15)
        self.takao_sum_vol_label.setFont(font)
        self.takao_sum_vol_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.takao_sum_vol_label.setLineWidth(1)
        self.takao_sum_vol_label.setObjectName("takao_sum_vol_label")
        self.takao_sum_ns_label = QtWidgets.QLabel(self.takao_sum_frame)
        self.takao_sum_ns_label.setGeometry(QtCore.QRect(10, 70, 251, 21))
        font = QtGui.QFont()
        font.setPixelSize(15)
        self.takao_sum_ns_label.setFont(font)
        self.takao_sum_ns_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.takao_sum_ns_label.setObjectName("takao_sum_ns_label")
        self.takao_sum_jm_label = QtWidgets.QLabel(self.takao_sum_frame)
        self.takao_sum_jm_label.setGeometry(QtCore.QRect(10, 90, 251, 21))
        font = QtGui.QFont()
        font.setPixelSize(15)
        self.takao_sum_jm_label.setFont(font)
        self.takao_sum_jm_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.takao_sum_jm_label.setObjectName("takao_sum_jm_label")
        self.yasuhiko_sum_frame = QtWidgets.QFrame(self.summary_frame)
        self.yasuhiko_sum_frame.setGeometry(QtCore.QRect(880, 30, 281, 131))
        font = QtGui.QFont()
        font.setPixelSize(29)
        self.yasuhiko_sum_frame.setFont(font)
        self.yasuhiko_sum_frame.setStyleSheet("color: rgb(255, 255, 255);")
        self.yasuhiko_sum_frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.yasuhiko_sum_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.yasuhiko_sum_frame.setLineWidth(10)
        self.yasuhiko_sum_frame.setMidLineWidth(10)
        self.yasuhiko_sum_frame.setObjectName("yasuhiko_sum_frame")
        self.yasuhiko_sum_label = QtWidgets.QLabel(self.yasuhiko_sum_frame)
        self.yasuhiko_sum_label.setGeometry(QtCore.QRect(10, 10, 161, 31))
        font = QtGui.QFont()
        font.setPixelSize(19)
        self.yasuhiko_sum_label.setFont(font)
        self.yasuhiko_sum_label.setObjectName("yasuhiko_sum_label")
        self.yasuhiko_sum_ns_label = QtWidgets.QLabel(self.yasuhiko_sum_frame)
        self.yasuhiko_sum_ns_label.setGeometry(QtCore.QRect(10, 70, 251, 21))
        font = QtGui.QFont()
        font.setPixelSize(15)
        self.yasuhiko_sum_ns_label.setFont(font)
        self.yasuhiko_sum_ns_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.yasuhiko_sum_ns_label.setObjectName("yasuhiko_sum_ns_label")
        self.yasuhiko_sum_jm_label = QtWidgets.QLabel(self.yasuhiko_sum_frame)
        self.yasuhiko_sum_jm_label.setGeometry(QtCore.QRect(10, 90, 251, 21))
        font = QtGui.QFont()
        font.setPixelSize(15)
        self.yasuhiko_sum_jm_label.setFont(font)
        self.yasuhiko_sum_jm_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.yasuhiko_sum_jm_label.setObjectName("yasuhiko_sum_jm_label")
        self.yasuhiko_sum_vol_label = QtWidgets.QLabel(self.yasuhiko_sum_frame)
        self.yasuhiko_sum_vol_label.setGeometry(QtCore.QRect(10, 50, 251, 21))
        font = QtGui.QFont()
        font.setPixelSize(15)
        self.yasuhiko_sum_vol_label.setFont(font)
        self.yasuhiko_sum_vol_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.yasuhiko_sum_vol_label.setLineWidth(1)
        self.yasuhiko_sum_vol_label.setObjectName("yasuhiko_sum_vol_label")
        self.contribution_frame = QtWidgets.QFrame(self.summary_frame)
        self.contribution_frame.setGeometry(QtCore.QRect(1180, 30, 441, 131))
        font = QtGui.QFont()
        font.setPixelSize(29)
        self.contribution_frame.setFont(font)
        self.contribution_frame.setStyleSheet("color: rgb(255, 255, 255);")
        self.contribution_frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.contribution_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.contribution_frame.setLineWidth(10)
        self.contribution_frame.setMidLineWidth(10)
        self.contribution_frame.setObjectName("contribution_frame")
        self.contribution_chart = QtWidgets.QGridLayout(self.contribution_frame)
        self.contribution_chart.setGeometry(QtCore.QRect(10, 10, 421, 111))
        self.contribution_chart.setObjectName("contribution_chart")
        self.ns_frame = QtWidgets.QFrame(self.summary_frame)
        self.ns_frame.setGeometry(QtCore.QRect(10, 530, 771, 351))
        font = QtGui.QFont()
        font.setPixelSize(29)
        self.ns_frame.setFont(font)
        self.ns_frame.setStyleSheet("color: rgb(255, 255, 255);")
        self.ns_frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.ns_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ns_frame.setLineWidth(10)
        self.ns_frame.setMidLineWidth(10)
        self.ns_frame.setObjectName("ns_frame")
        self.ns_chart = QtWidgets.QGridLayout(self.ns_frame)
        self.ns_chart.setGeometry(QtCore.QRect(10, 10, 751, 331))
        self.ns_chart.setObjectName("ns_chart")
        self.vol_frame = QtWidgets.QFrame(self.summary_frame)
        self.vol_frame.setGeometry(QtCore.QRect(800, 530, 821, 351))
        font = QtGui.QFont()
        font.setPixelSize(29)
        self.vol_frame.setFont(font)
        self.vol_frame.setStyleSheet("color: rgb(255, 255, 255);")
        self.vol_frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.vol_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.vol_frame.setLineWidth(10)
        self.vol_frame.setMidLineWidth(10)
        self.vol_frame.setObjectName("vol_frame")
        self.vol_chart = QtWidgets.QGridLayout(self.vol_frame)
        self.vol_chart.setGeometry(QtCore.QRect(10, 10, 801, 331))
        self.vol_chart.setObjectName("vol_chart")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.kota_frame = QtWidgets.QFrame(self.tab_2)
        self.kota_frame.setGeometry(QtCore.QRect(0, 0, 1751, 905))
        self.kota_frame.setObjectName("kota_frame")
        self.kota_jm_frame = QtWidgets.QFrame(self.kota_frame)
        self.kota_jm_frame.setGeometry(QtCore.QRect(10, 170, 791, 351))
        font = QtGui.QFont()
        font.setPixelSize(29)
        self.kota_jm_frame.setFont(font)
        self.kota_jm_frame.setStyleSheet("color: rgb(255, 255, 255);")
        self.kota_jm_frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.kota_jm_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.kota_jm_frame.setLineWidth(10)
        self.kota_jm_frame.setMidLineWidth(10)
        self.kota_jm_frame.setObjectName("kota_jm_frame")
        self.kota_jm_chart = QtWidgets.QGridLayout(self.kota_jm_frame)
        self.kota_jm_chart.setGeometry(QtCore.QRect(10, 10, 771, 331))
        self.kota_jm_chart.setObjectName("kota_jm_chart")
        self.kota_fc_frame = QtWidgets.QFrame(self.kota_frame)
        self.kota_fc_frame.setGeometry(QtCore.QRect(10, 30, 791, 121))
        font = QtGui.QFont()
        font.setPixelSize(29)
        self.kota_fc_frame.setFont(font)
        self.kota_fc_frame.setStyleSheet("color: rgb(255, 255, 255);")
        self.kota_fc_frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.kota_fc_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.kota_fc_frame.setLineWidth(10)
        self.kota_fc_frame.setMidLineWidth(10)
        self.kota_fc_frame.setObjectName("kota_fc_frame")
        self.kota_fc_table = QtWidgets.QTableView(self.kota_fc_frame)
        self.kota_fc_table.setGeometry(QtCore.QRect(10, 10, 771, 101))
        self.kota_fc_table.setObjectName("kota_fc_table")
        self.kota_vol_frame = QtWidgets.QFrame(self.kota_frame)
        self.kota_vol_frame.setGeometry(QtCore.QRect(10, 530, 791, 351))
        font = QtGui.QFont()
        font.setPixelSize(29)
        self.kota_vol_frame.setFont(font)
        self.kota_vol_frame.setStyleSheet("color: rgb(255, 255, 255);")
        self.kota_vol_frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.kota_vol_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.kota_vol_frame.setLineWidth(10)
        self.kota_vol_frame.setMidLineWidth(10)
        self.kota_vol_frame.setObjectName("kota_vol_frame")
        self.kota_vol_chart = QtWidgets.QGridLayout(self.kota_vol_frame)
        self.kota_vol_chart.setGeometry(QtCore.QRect(10, 10, 771, 331))
        self.kota_vol_chart.setObjectName("kota_vol_chart")
        self.kota_ns_frame = QtWidgets.QFrame(self.kota_frame)
        self.kota_ns_frame.setGeometry(QtCore.QRect(830, 170, 791, 351))
        font = QtGui.QFont()
        font.setPixelSize(29)
        self.kota_ns_frame.setFont(font)
        self.kota_ns_frame.setStyleSheet("color: rgb(255, 255, 255);")
        self.kota_ns_frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.kota_ns_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.kota_ns_frame.setLineWidth(10)
        self.kota_ns_frame.setMidLineWidth(10)
        self.kota_ns_frame.setObjectName("kota_ns_frame")
        self.kota_ns_chart = QtWidgets.QGridLayout(self.kota_ns_frame)
        self.kota_ns_chart.setGeometry(QtCore.QRect(10, 10, 771, 331))
        self.kota_ns_chart.setObjectName("kota_ns_chart")
        self.kota_customers_frame = QtWidgets.QFrame(self.kota_frame)
        self.kota_customers_frame.setGeometry(QtCore.QRect(830, 530, 791, 351))
        font = QtGui.QFont()
        font.setPixelSize(29)
        self.kota_customers_frame.setFont(font)
        self.kota_customers_frame.setStyleSheet("color: rgb(255, 255, 255);")
        self.kota_customers_frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.kota_customers_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.kota_customers_frame.setLineWidth(10)
        self.kota_customers_frame.setMidLineWidth(10)
        self.kota_customers_frame.setObjectName("kota_customers_frame")
        self.kota_customers_chart = QtWidgets.QGridLayout(self.kota_customers_frame)
        self.kota_customers_chart.setGeometry(QtCore.QRect(10, 10, 771, 331))
        self.kota_customers_chart.setObjectName("kota_customers_chart")
        self.kota_open_frame = QtWidgets.QFrame(self.kota_frame)
        self.kota_open_frame.setGeometry(QtCore.QRect(830, 30, 181, 121))
        font = QtGui.QFont()
        font.setPixelSize(29)
        self.kota_open_frame.setFont(font)
        self.kota_open_frame.setStyleSheet("color: rgb(255, 255, 255);")
        self.kota_open_frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.kota_open_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.kota_open_frame.setLineWidth(10)
        self.kota_open_frame.setMidLineWidth(10)
        self.kota_open_frame.setObjectName("kota_open_frame")
        self.kota_open_label = QtWidgets.QLabel(self.kota_open_frame)
        self.kota_open_label.setGeometry(QtCore.QRect(10, 10, 161, 41))
        font = QtGui.QFont()
        font.setPixelSize(20)
        self.kota_open_label.setFont(font)
        self.kota_open_label.setObjectName("kota_open_label")
        self.kota_open_num_label = QtWidgets.QLabel(self.kota_open_frame)
        self.kota_open_num_label.setGeometry(QtCore.QRect(80, 50, 61, 51))
        font = QtGui.QFont()
        font.setPixelSize(39)
        self.kota_open_num_label.setFont(font)
        self.kota_open_num_label.setObjectName("kota_open_num_label")
        self.kota_win_frame = QtWidgets.QFrame(self.kota_frame)
        self.kota_win_frame.setGeometry(QtCore.QRect(1240, 30, 181, 121))
        font = QtGui.QFont()
        font.setPixelSize(29)
        self.kota_win_frame.setFont(font)
        self.kota_win_frame.setStyleSheet("color: rgb(255, 255, 255);")
        self.kota_win_frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.kota_win_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.kota_win_frame.setLineWidth(10)
        self.kota_win_frame.setMidLineWidth(10)
        self.kota_win_frame.setObjectName("kota_win_frame")
        self.kota_win_label = QtWidgets.QLabel(self.kota_win_frame)
        self.kota_win_label.setGeometry(QtCore.QRect(30, 10, 131, 41))
        font = QtGui.QFont()
        font.setPixelSize(20)
        self.kota_win_label.setFont(font)
        self.kota_win_label.setObjectName("kota_win_label")
        self.kota_win_num1_label = QtWidgets.QLabel(self.kota_win_frame)
        self.kota_win_num1_label.setGeometry(QtCore.QRect(30, 50, 61, 21))
        font = QtGui.QFont()
        font.setPixelSize(30)
        self.kota_win_num1_label.setFont(font)
        self.kota_win_num1_label.setObjectName("kota_win_num1_label")
        self.kota_win_num2_label = QtWidgets.QLabel(self.kota_win_frame)
        self.kota_win_num2_label.setGeometry(QtCore.QRect(30, 80, 61, 21))
        font = QtGui.QFont()
        font.setPixelSize(30)
        self.kota_win_num2_label.setFont(font)
        self.kota_win_num2_label.setObjectName("kota_win_num2_label")
        self.kota_outstanding_frame = QtWidgets.QFrame(self.kota_frame)
        self.kota_outstanding_frame.setGeometry(QtCore.QRect(1440, 30, 181, 121))
        font = QtGui.QFont()
        font.setPixelSize(29)
        self.kota_outstanding_frame.setFont(font)
        self.kota_outstanding_frame.setStyleSheet("color: rgb(255, 255, 255);")
        self.kota_outstanding_frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.kota_outstanding_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.kota_outstanding_frame.setLineWidth(10)
        self.kota_outstanding_frame.setMidLineWidth(10)
        self.kota_outstanding_frame.setObjectName("kota_outstanding_frame")
        self.kota_outstanding_label = QtWidgets.QLabel(self.kota_outstanding_frame)
        self.kota_outstanding_label.setGeometry(QtCore.QRect(20, 10, 151, 41))
        font = QtGui.QFont()
        font.setPixelSize(20)
        self.kota_outstanding_label.setFont(font)
        self.kota_outstanding_label.setObjectName("kota_outstanding_label")
        self.kota_doubts_label = QtWidgets.QLabel(self.kota_outstanding_frame)
        self.kota_doubts_label.setGeometry(QtCore.QRect(10, 50, 101, 21))
        font = QtGui.QFont()
        font.setPixelSize(12)
        self.kota_doubts_label.setFont(font)
        self.kota_doubts_label.setObjectName("kota_doubts_label")
        self.kota_uncommented_label = QtWidgets.QLabel(self.kota_outstanding_frame)
        self.kota_uncommented_label.setGeometry(QtCore.QRect(10, 90, 101, 21))
        font = QtGui.QFont()
        font.setPixelSize(12)
        self.kota_uncommented_label.setFont(font)
        self.kota_uncommented_label.setObjectName("kota_uncommented_label")
        self.line = QtWidgets.QFrame(self.kota_outstanding_frame)
        self.line.setGeometry(QtCore.QRect(90, 50, 16, 61))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.kota_doubts_num1_label = QtWidgets.QLabel(self.kota_outstanding_frame)
        self.kota_doubts_num1_label.setGeometry(QtCore.QRect(100, 50, 61, 21))
        font = QtGui.QFont()
        font.setPixelSize(11)
        self.kota_doubts_num1_label.setFont(font)
        self.kota_doubts_num1_label.setObjectName("kota_doubts_num1_label")
        self.kota_doubts_num2_label = QtWidgets.QLabel(self.kota_outstanding_frame)
        self.kota_doubts_num2_label.setGeometry(QtCore.QRect(100, 70, 61, 21))
        font = QtGui.QFont()
        font.setPixelSize(11)
        self.kota_doubts_num2_label.setFont(font)
        self.kota_doubts_num2_label.setObjectName("kota_doubts_num2_label")
        self.kota_uncommented_num_label = QtWidgets.QLabel(self.kota_outstanding_frame)
        self.kota_uncommented_num_label.setGeometry(QtCore.QRect(100, 90, 61, 21))
        font = QtGui.QFont()
        font.setPixelSize(11)
        self.kota_uncommented_num_label.setFont(font)
        self.kota_uncommented_num_label.setObjectName("kota_uncommented_num_label")
        self.kota_total_frame = QtWidgets.QFrame(self.kota_frame)
        self.kota_total_frame.setGeometry(QtCore.QRect(1040, 30, 181, 121))
        font = QtGui.QFont()
        font.setPixelSize(29)
        self.kota_total_frame.setFont(font)
        self.kota_total_frame.setStyleSheet("color: rgb(255, 255, 255);")
        self.kota_total_frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.kota_total_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.kota_total_frame.setLineWidth(10)
        self.kota_total_frame.setMidLineWidth(10)
        self.kota_total_frame.setObjectName("kota_total_frame")
        self.kota_total_label = QtWidgets.QLabel(self.kota_total_frame)
        self.kota_total_label.setGeometry(QtCore.QRect(20, 10, 141, 41))
        font = QtGui.QFont()
        font.setPixelSize(20)
        self.kota_total_label.setFont(font)
        self.kota_total_label.setObjectName("kota_total_label")
        self.kota_total_num_label = QtWidgets.QLabel(self.kota_total_frame)
        self.kota_total_num_label.setGeometry(QtCore.QRect(20, 50, 61, 51))
        font = QtGui.QFont()
        font.setPixelSize(39)
        self.kota_total_num_label.setFont(font)
        self.kota_total_num_label.setObjectName("kota_total_num_label")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.seiichi_frame = QtWidgets.QFrame(self.tab_3)
        self.seiichi_frame.setGeometry(QtCore.QRect(0, 0, 1631, 905))
        self.seiichi_frame.setObjectName("seiichi_frame")
        self.seiichi_jm_frame = QtWidgets.QFrame(self.seiichi_frame)
        self.seiichi_jm_frame.setGeometry(QtCore.QRect(10, 170, 791, 351))
        font = QtGui.QFont()
        font.setPixelSize(29)
        self.seiichi_jm_frame.setFont(font)
        self.seiichi_jm_frame.setStyleSheet("color: rgb(255, 255, 255);")
        self.seiichi_jm_frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.seiichi_jm_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seiichi_jm_frame.setLineWidth(10)
        self.seiichi_jm_frame.setMidLineWidth(10)
        self.seiichi_jm_frame.setObjectName("seiichi_jm_frame")
        self.seiichi_jm_chart = QtWidgets.QGridLayout(self.seiichi_jm_frame)
        self.seiichi_jm_chart.setGeometry(QtCore.QRect(10, 10, 771, 331))
        self.seiichi_jm_chart.setObjectName("seiichi_jm_chart")
        self.seiichi_fc_frame = QtWidgets.QFrame(self.seiichi_frame)
        self.seiichi_fc_frame.setGeometry(QtCore.QRect(10, 30, 791, 121))
        font = QtGui.QFont()
        font.setPixelSize(29)
        self.seiichi_fc_frame.setFont(font)
        self.seiichi_fc_frame.setStyleSheet("color: rgb(255, 255, 255);")
        self.seiichi_fc_frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.seiichi_fc_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seiichi_fc_frame.setLineWidth(10)
        self.seiichi_fc_frame.setMidLineWidth(10)
        self.seiichi_fc_frame.setObjectName("seiichi_fc_frame")
        self.seiichi_fc_table = QtWidgets.QTableView(self.seiichi_fc_frame)
        self.seiichi_fc_table.setGeometry(QtCore.QRect(10, 10, 771, 101))
        self.seiichi_fc_table.setObjectName("seiichi_fc_table")
        self.seiichi_vol_frame = QtWidgets.QFrame(self.seiichi_frame)
        self.seiichi_vol_frame.setGeometry(QtCore.QRect(10, 530, 791, 351))
        font = QtGui.QFont()
        font.setPixelSize(29)
        self.seiichi_vol_frame.setFont(font)
        self.seiichi_vol_frame.setStyleSheet("color: rgb(255, 255, 255);")
        self.seiichi_vol_frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.seiichi_vol_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seiichi_vol_frame.setLineWidth(10)
        self.seiichi_vol_frame.setMidLineWidth(10)
        self.seiichi_vol_frame.setObjectName("seiichi_vol_frame")
        self.seiichi_vol_chart = QtWidgets.QGridLayout(self.seiichi_vol_frame)
        self.seiichi_vol_chart.setGeometry(QtCore.QRect(10, 10, 771, 331))
        self.seiichi_vol_chart.setObjectName("seiichi_vol_chart")
        self.seiichi_ns_frame = QtWidgets.QFrame(self.seiichi_frame)
        self.seiichi_ns_frame.setGeometry(QtCore.QRect(830, 170, 791, 351))
        font = QtGui.QFont()
        font.setPixelSize(29)
        self.seiichi_ns_frame.setFont(font)
        self.seiichi_ns_frame.setStyleSheet("color: rgb(255, 255, 255);")
        self.seiichi_ns_frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.seiichi_ns_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seiichi_ns_frame.setLineWidth(10)
        self.seiichi_ns_frame.setMidLineWidth(10)
        self.seiichi_ns_frame.setObjectName("seiichi_ns_frame")
        self.seiichi_ns_chart = QtWidgets.QGridLayout(self.seiichi_ns_frame)
        self.seiichi_ns_chart.setGeometry(QtCore.QRect(10, 10, 771, 331))
        self.seiichi_ns_chart.setObjectName("seiichi_ns_chart")
        self.seiichi_customers_frame = QtWidgets.QFrame(self.seiichi_frame)
        self.seiichi_customers_frame.setGeometry(QtCore.QRect(830, 530, 791, 351))
        font = QtGui.QFont()
        font.setPixelSize(29)
        self.seiichi_customers_frame.setFont(font)
        self.seiichi_customers_frame.setStyleSheet("color: rgb(255, 255, 255);")
        self.seiichi_customers_frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.seiichi_customers_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seiichi_customers_frame.setLineWidth(10)
        self.seiichi_customers_frame.setMidLineWidth(10)
        self.seiichi_customers_frame.setObjectName("seiichi_customers_frame")
        self.seiichi_customers_chart = QtWidgets.QGridLayout(self.seiichi_customers_frame)
        self.seiichi_customers_chart.setGeometry(QtCore.QRect(10, 10, 771, 331))
        self.seiichi_customers_chart.setObjectName("seiichi_customers_chart")
        self.seiichi_open_frame = QtWidgets.QFrame(self.seiichi_frame)
        self.seiichi_open_frame.setGeometry(QtCore.QRect(830, 30, 181, 121))
        font = QtGui.QFont()
        font.setPixelSize(29)
        self.seiichi_open_frame.setFont(font)
        self.seiichi_open_frame.setStyleSheet("color: rgb(255, 255, 255);")
        self.seiichi_open_frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.seiichi_open_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seiichi_open_frame.setLineWidth(10)
        self.seiichi_open_frame.setMidLineWidth(10)
        self.seiichi_open_frame.setObjectName("seiichi_open_frame")
        self.seiichi_open_label = QtWidgets.QLabel(self.seiichi_open_frame)
        self.seiichi_open_label.setGeometry(QtCore.QRect(10, 10, 161, 41))
        font = QtGui.QFont()
        font.setPixelSize(20)
        self.seiichi_open_label.setFont(font)
        self.seiichi_open_label.setObjectName("seiichi_open_label")
        self.seiichi_open_num_label = QtWidgets.QLabel(self.seiichi_open_frame)
        self.seiichi_open_num_label.setGeometry(QtCore.QRect(80, 50, 61, 51))
        font = QtGui.QFont()
        font.setPixelSize(39)
        self.seiichi_open_num_label.setFont(font)
        self.seiichi_open_num_label.setObjectName("seiichi_open_num_label")
        self.seiichi_win_frame = QtWidgets.QFrame(self.seiichi_frame)
        self.seiichi_win_frame.setGeometry(QtCore.QRect(1240, 30, 181, 121))
        font = QtGui.QFont()
        font.setPixelSize(29)
        self.seiichi_win_frame.setFont(font)
        self.seiichi_win_frame.setStyleSheet("color: rgb(255, 255, 255);")
        self.seiichi_win_frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.seiichi_win_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seiichi_win_frame.setLineWidth(10)
        self.seiichi_win_frame.setMidLineWidth(10)
        self.seiichi_win_frame.setObjectName("seiichi_win_frame")
        self.seiichi_win_label = QtWidgets.QLabel(self.seiichi_win_frame)
        self.seiichi_win_label.setGeometry(QtCore.QRect(30, 10, 131, 41))
        font = QtGui.QFont()
        font.setPixelSize(20)
        self.seiichi_win_label.setFont(font)
        self.seiichi_win_label.setObjectName("seiichi_win_label")
        self.seiichi_win_num1_label = QtWidgets.QLabel(self.seiichi_win_frame)
        self.seiichi_win_num1_label.setGeometry(QtCore.QRect(30, 50, 61, 21))
        font = QtGui.QFont()
        font.setPixelSize(30)
        self.seiichi_win_num1_label.setFont(font)
        self.seiichi_win_num1_label.setObjectName("seiichi_win_num1_label")
        self.seiichi_win_num2_label = QtWidgets.QLabel(self.seiichi_win_frame)
        self.seiichi_win_num2_label.setGeometry(QtCore.QRect(30, 80, 61, 21))
        font = QtGui.QFont()
        font.setPixelSize(30)
        self.seiichi_win_num2_label.setFont(font)
        self.seiichi_win_num2_label.setObjectName("seiichi_win_num2_label")
        self.seiichi_outstanding_frame = QtWidgets.QFrame(self.seiichi_frame)
        self.seiichi_outstanding_frame.setGeometry(QtCore.QRect(1440, 30, 181, 121))
        font = QtGui.QFont()
        font.setPixelSize(29)
        self.seiichi_outstanding_frame.setFont(font)
        self.seiichi_outstanding_frame.setStyleSheet("color: rgb(255, 255, 255);")
        self.seiichi_outstanding_frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.seiichi_outstanding_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seiichi_outstanding_frame.setLineWidth(10)
        self.seiichi_outstanding_frame.setMidLineWidth(10)
        self.seiichi_outstanding_frame.setObjectName("seiichi_outstanding_frame")
        self.seiichi_outstanding_label = QtWidgets.QLabel(self.seiichi_outstanding_frame)
        self.seiichi_outstanding_label.setGeometry(QtCore.QRect(20, 10, 151, 41))
        font = QtGui.QFont()
        font.setPixelSize(20)
        self.seiichi_outstanding_label.setFont(font)
        self.seiichi_outstanding_label.setObjectName("seiichi_outstanding_label")
        self.seiichi_doubts_label = QtWidgets.QLabel(self.seiichi_outstanding_frame)
        self.seiichi_doubts_label.setGeometry(QtCore.QRect(10, 50, 101, 21))
        font = QtGui.QFont()
        font.setPixelSize(12)
        self.seiichi_doubts_label.setFont(font)
        self.seiichi_doubts_label.setObjectName("seiichi_doubts_label")
        self.seiichi_uncommented_label = QtWidgets.QLabel(self.seiichi_outstanding_frame)
        self.seiichi_uncommented_label.setGeometry(QtCore.QRect(10, 90, 101, 21))
        font = QtGui.QFont()
        font.setPixelSize(12)
        self.seiichi_uncommented_label.setFont(font)
        self.seiichi_uncommented_label.setObjectName("seiichi_uncommented_label")
        self.line_2 = QtWidgets.QFrame(self.seiichi_outstanding_frame)
        self.line_2.setGeometry(QtCore.QRect(90, 50, 16, 61))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.seiichi_doubts_num1_label = QtWidgets.QLabel(self.seiichi_outstanding_frame)
        self.seiichi_doubts_num1_label.setGeometry(QtCore.QRect(100, 50, 61, 21))
        font = QtGui.QFont()
        font.setPixelSize(11)
        self.seiichi_doubts_num1_label.setFont(font)
        self.seiichi_doubts_num1_label.setObjectName("seiichi_doubts_num1_label")
        self.seiichi_doubts_num2_label = QtWidgets.QLabel(self.seiichi_outstanding_frame)
        self.seiichi_doubts_num2_label.setGeometry(QtCore.QRect(100, 70, 51, 21))
        font = QtGui.QFont()
        font.setPixelSize(11)
        self.seiichi_doubts_num2_label.setFont(font)
        self.seiichi_doubts_num2_label.setObjectName("seiichi_doubts_num2_label")
        self.seiichi_uncommented_num_label = QtWidgets.QLabel(self.seiichi_outstanding_frame)
        self.seiichi_uncommented_num_label.setGeometry(QtCore.QRect(100, 90, 61, 21))
        font = QtGui.QFont()
        font.setPixelSize(11)
        self.seiichi_uncommented_num_label.setFont(font)
        self.seiichi_uncommented_num_label.setObjectName("seiichi_uncommented_num_label")
        self.seiichi_total_frame = QtWidgets.QFrame(self.seiichi_frame)
        self.seiichi_total_frame.setGeometry(QtCore.QRect(1040, 30, 181, 121))
        font = QtGui.QFont()
        font.setPixelSize(29)
        self.seiichi_total_frame.setFont(font)
        self.seiichi_total_frame.setStyleSheet("color: rgb(255, 255, 255);")
        self.seiichi_total_frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.seiichi_total_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seiichi_total_frame.setLineWidth(10)
        self.seiichi_total_frame.setMidLineWidth(10)
        self.seiichi_total_frame.setObjectName("seiichi_total_frame")
        self.seiichi_total_label = QtWidgets.QLabel(self.seiichi_total_frame)
        self.seiichi_total_label.setGeometry(QtCore.QRect(20, 10, 151, 41))
        font = QtGui.QFont()
        font.setPixelSize(20)
        self.seiichi_total_label.setFont(font)
        self.seiichi_total_label.setObjectName("seiichi_total_label")
        self.seiichi_total_num_label = QtWidgets.QLabel(self.seiichi_total_frame)
        self.seiichi_total_num_label.setGeometry(QtCore.QRect(20, 50, 61, 51))
        font = QtGui.QFont()
        font.setPixelSize(39)
        self.seiichi_total_num_label.setFont(font)
        self.seiichi_total_num_label.setObjectName("seiichi_total_num_label")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.takao_frame = QtWidgets.QFrame(self.tab_4)
        self.takao_frame.setGeometry(QtCore.QRect(0, 0, 1631, 905))
        self.takao_frame.setObjectName("takao_frame")
        self.takao_jm_frame = QtWidgets.QFrame(self.takao_frame)
        self.takao_jm_frame.setGeometry(QtCore.QRect(10, 170, 791, 351))
        font = QtGui.QFont()
        font.setPixelSize(29)
        self.takao_jm_frame.setFont(font)
        self.takao_jm_frame.setStyleSheet("color: rgb(255, 255, 255);")
        self.takao_jm_frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.takao_jm_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.takao_jm_frame.setLineWidth(10)
        self.takao_jm_frame.setMidLineWidth(10)
        self.takao_jm_frame.setObjectName("takao_jm_frame")
        self.takao_jm_chart = QtWidgets.QGridLayout(self.takao_jm_frame)
        self.takao_jm_chart.setGeometry(QtCore.QRect(10, 10, 771, 331))
        self.takao_jm_chart.setObjectName("takao_jm_chart")
        self.takao_fc_frame = QtWidgets.QFrame(self.takao_frame)
        self.takao_fc_frame.setGeometry(QtCore.QRect(10, 30, 791, 121))
        font = QtGui.QFont()
        font.setPixelSize(29)
        self.takao_fc_frame.setFont(font)
        self.takao_fc_frame.setStyleSheet("color: rgb(255, 255, 255);")
        self.takao_fc_frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.takao_fc_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.takao_fc_frame.setLineWidth(10)
        self.takao_fc_frame.setMidLineWidth(10)
        self.takao_fc_frame.setObjectName("takao_fc_frame")
        self.takao_fc_table = QtWidgets.QTableView(self.takao_fc_frame)
        self.takao_fc_table.setGeometry(QtCore.QRect(10, 10, 771, 101))
        self.takao_fc_table.setObjectName("takao_fc_table")
        self.takao_vol_frame = QtWidgets.QFrame(self.takao_frame)
        self.takao_vol_frame.setGeometry(QtCore.QRect(10, 530, 791, 351))
        font = QtGui.QFont()
        font.setPixelSize(29)
        self.takao_vol_frame.setFont(font)
        self.takao_vol_frame.setStyleSheet("color: rgb(255, 255, 255);")
        self.takao_vol_frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.takao_vol_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.takao_vol_frame.setLineWidth(10)
        self.takao_vol_frame.setMidLineWidth(10)
        self.takao_vol_frame.setObjectName("takao_vol_frame")
        self.takao_vol_chart = QtWidgets.QGridLayout(self.takao_vol_frame)
        self.takao_vol_chart.setGeometry(QtCore.QRect(10, 10, 771, 331))
        self.takao_vol_chart.setObjectName("takao_vol_chart")
        self.takao_ns_frame = QtWidgets.QFrame(self.takao_frame)
        self.takao_ns_frame.setGeometry(QtCore.QRect(830, 170, 791, 351))
        font = QtGui.QFont()
        font.setPixelSize(29)
        self.takao_ns_frame.setFont(font)
        self.takao_ns_frame.setStyleSheet("color: rgb(255, 255, 255);")
        self.takao_ns_frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.takao_ns_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.takao_ns_frame.setLineWidth(10)
        self.takao_ns_frame.setMidLineWidth(10)
        self.takao_ns_frame.setObjectName("takao_ns_frame")
        self.takao_ns_chart = QtWidgets.QGridLayout(self.takao_ns_frame)
        self.takao_ns_chart.setGeometry(QtCore.QRect(10, 10, 771, 331))
        self.takao_ns_chart.setObjectName("takao_ns_chart")
        self.takao_customers_frame = QtWidgets.QFrame(self.takao_frame)
        self.takao_customers_frame.setGeometry(QtCore.QRect(830, 530, 791, 351))
        font = QtGui.QFont()
        font.setPixelSize(29)
        self.takao_customers_frame.setFont(font)
        self.takao_customers_frame.setStyleSheet("color: rgb(255, 255, 255);")
        self.takao_customers_frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.takao_customers_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.takao_customers_frame.setLineWidth(10)
        self.takao_customers_frame.setMidLineWidth(10)
        self.takao_customers_frame.setObjectName("takao_customers_frame")
        self.takao_customers_chart = QtWidgets.QGridLayout(self.takao_customers_frame)
        self.takao_customers_chart.setGeometry(QtCore.QRect(10, 10, 771, 331))
        self.takao_customers_chart.setObjectName("takao_customers_chart")
        self.takao_open_frame_2 = QtWidgets.QFrame(self.takao_frame)
        self.takao_open_frame_2.setGeometry(QtCore.QRect(830, 30, 181, 121))
        font = QtGui.QFont()
        font.setPixelSize(29)
        self.takao_open_frame_2.setFont(font)
        self.takao_open_frame_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.takao_open_frame_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.takao_open_frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.takao_open_frame_2.setLineWidth(10)
        self.takao_open_frame_2.setMidLineWidth(10)
        self.takao_open_frame_2.setObjectName("takao_open_frame_2")
        self.takao_open_label = QtWidgets.QLabel(self.takao_open_frame_2)
        self.takao_open_label.setGeometry(QtCore.QRect(10, 10, 161, 41))
        font = QtGui.QFont()
        font.setPixelSize(20)
        self.takao_open_label.setFont(font)
        self.takao_open_label.setObjectName("takao_open_label")
        self.takao_open_num_label = QtWidgets.QLabel(self.takao_open_frame_2)
        self.takao_open_num_label.setGeometry(QtCore.QRect(80, 50, 61, 51))
        font = QtGui.QFont()
        font.setPixelSize(39)
        self.takao_open_num_label.setFont(font)
        self.takao_open_num_label.setObjectName("takao_open_num_label")
        self.takao_win_frame = QtWidgets.QFrame(self.takao_frame)
        self.takao_win_frame.setGeometry(QtCore.QRect(1240, 30, 181, 121))
        font = QtGui.QFont()
        font.setPixelSize(29)
        self.takao_win_frame.setFont(font)
        self.takao_win_frame.setStyleSheet("color: rgb(255, 255, 255);")
        self.takao_win_frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.takao_win_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.takao_win_frame.setLineWidth(10)
        self.takao_win_frame.setMidLineWidth(10)
        self.takao_win_frame.setObjectName("takao_win_frame")
        self.takao_win_label = QtWidgets.QLabel(self.takao_win_frame)
        self.takao_win_label.setGeometry(QtCore.QRect(30, 10, 141, 41))
        font = QtGui.QFont()
        font.setPixelSize(20)
        self.takao_win_label.setFont(font)
        self.takao_win_label.setObjectName("takao_win_label")
        self.takao_win_num1_label = QtWidgets.QLabel(self.takao_win_frame)
        self.takao_win_num1_label.setGeometry(QtCore.QRect(30, 50, 141, 21))
        font = QtGui.QFont()
        font.setPixelSize(30)
        self.takao_win_num1_label.setFont(font)
        self.takao_win_num1_label.setObjectName("takao_win_num1_label")
        self.takao_win_num2_label = QtWidgets.QLabel(self.takao_win_frame)
        self.takao_win_num2_label.setGeometry(QtCore.QRect(30, 80, 141, 21))
        font = QtGui.QFont()
        font.setPixelSize(30)
        self.takao_win_num2_label.setFont(font)
        self.takao_win_num2_label.setObjectName("takao_win_num2_label")
        self.takao_outstanding_frame = QtWidgets.QFrame(self.takao_frame)
        self.takao_outstanding_frame.setGeometry(QtCore.QRect(1440, 30, 181, 121))
        font = QtGui.QFont()
        font.setPixelSize(29)
        self.takao_outstanding_frame.setFont(font)
        self.takao_outstanding_frame.setStyleSheet("color: rgb(255, 255, 255);")
        self.takao_outstanding_frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.takao_outstanding_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.takao_outstanding_frame.setLineWidth(10)
        self.takao_outstanding_frame.setMidLineWidth(10)
        self.takao_outstanding_frame.setObjectName("takao_outstanding_frame")
        self.takao_outstanding_label = QtWidgets.QLabel(self.takao_outstanding_frame)
        self.takao_outstanding_label.setGeometry(QtCore.QRect(20, 10, 151, 41))
        font = QtGui.QFont()
        font.setPixelSize(20)
        self.takao_outstanding_label.setFont(font)
        self.takao_outstanding_label.setObjectName("takao_outstanding_label")
        self.takao_doubts_label = QtWidgets.QLabel(self.takao_outstanding_frame)
        self.takao_doubts_label.setGeometry(QtCore.QRect(10, 50, 101, 21))
        font = QtGui.QFont()
        font.setPixelSize(12)
        self.takao_doubts_label.setFont(font)
        self.takao_doubts_label.setObjectName("takao_doubts_label")
        self.takao_uncommented_label = QtWidgets.QLabel(self.takao_outstanding_frame)
        self.takao_uncommented_label.setGeometry(QtCore.QRect(10, 90, 101, 21))
        font = QtGui.QFont()
        font.setPixelSize(12)
        self.takao_uncommented_label.setFont(font)
        self.takao_uncommented_label.setObjectName("takao_uncommented_label")
        self.line_3 = QtWidgets.QFrame(self.takao_outstanding_frame)
        self.line_3.setGeometry(QtCore.QRect(90, 40, 16, 61))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.takao_doubts_num1_label = QtWidgets.QLabel(self.takao_outstanding_frame)
        self.takao_doubts_num1_label.setGeometry(QtCore.QRect(100, 50, 61, 21))
        font = QtGui.QFont()
        font.setPixelSize(11)
        self.takao_doubts_num1_label.setFont(font)
        self.takao_doubts_num1_label.setObjectName("takao_doubts_num1_label")
        self.takao_doubts_num2_label = QtWidgets.QLabel(self.takao_outstanding_frame)
        self.takao_doubts_num2_label.setGeometry(QtCore.QRect(100, 70, 61, 21))
        font = QtGui.QFont()
        font.setPixelSize(11)
        self.takao_doubts_num2_label.setFont(font)
        self.takao_doubts_num2_label.setObjectName("takao_doubts_num2_label")
        self.takao_uncommented_num_label = QtWidgets.QLabel(self.takao_outstanding_frame)
        self.takao_uncommented_num_label.setGeometry(QtCore.QRect(100, 90, 61, 21))
        font = QtGui.QFont()
        font.setPixelSize(11)
        self.takao_uncommented_num_label.setFont(font)
        self.takao_uncommented_num_label.setObjectName("takao_uncommented_num_label")
        self.takao_total_frame = QtWidgets.QFrame(self.takao_frame)
        self.takao_total_frame.setGeometry(QtCore.QRect(1040, 30, 181, 121))
        font = QtGui.QFont()
        font.setPixelSize(29)
        self.takao_total_frame.setFont(font)
        self.takao_total_frame.setStyleSheet("color: rgb(255, 255, 255);")
        self.takao_total_frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.takao_total_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.takao_total_frame.setLineWidth(10)
        self.takao_total_frame.setMidLineWidth(10)
        self.takao_total_frame.setObjectName("takao_total_frame")
        self.takao_total_label = QtWidgets.QLabel(self.takao_total_frame)
        self.takao_total_label.setGeometry(QtCore.QRect(20, 10, 141, 41))
        font = QtGui.QFont()
        font.setPixelSize(20)
        self.takao_total_label.setFont(font)
        self.takao_total_label.setObjectName("takao_total_label")
        self.takao_total_num_label = QtWidgets.QLabel(self.takao_total_frame)
        self.takao_total_num_label.setGeometry(QtCore.QRect(20, 50, 151, 51))
        font = QtGui.QFont()
        font.setPixelSize(39)
        self.takao_total_num_label.setFont(font)
        self.takao_total_num_label.setObjectName("takao_total_num_label")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.takao_frame_2 = QtWidgets.QFrame(self.tab_5)
        self.takao_frame_2.setGeometry(QtCore.QRect(0, 0, 1631, 905))
        self.takao_frame_2.setObjectName("takao_frame_2")
        self.yasuhiko_jm_frame = QtWidgets.QFrame(self.takao_frame_2)
        self.yasuhiko_jm_frame.setGeometry(QtCore.QRect(10, 170, 791, 351))
        font = QtGui.QFont()
        font.setPixelSize(29)
        self.yasuhiko_jm_frame.setFont(font)
        self.yasuhiko_jm_frame.setStyleSheet("color: rgb(255, 255, 255);")
        self.yasuhiko_jm_frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.yasuhiko_jm_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.yasuhiko_jm_frame.setLineWidth(10)
        self.yasuhiko_jm_frame.setMidLineWidth(10)
        self.yasuhiko_jm_frame.setObjectName("yasuhiko_jm_frame")
        self.yasuhiko_jm_chart = QtWidgets.QGridLayout(self.yasuhiko_jm_frame)
        self.yasuhiko_jm_chart.setGeometry(QtCore.QRect(10, 10, 771, 331))
        self.yasuhiko_jm_chart.setObjectName("yasuhiko_jm_chart")
        self.yasuhiko_fc_frame = QtWidgets.QFrame(self.takao_frame_2)
        self.yasuhiko_fc_frame.setGeometry(QtCore.QRect(10, 30, 791, 121))
        font = QtGui.QFont()
        font.setPixelSize(29)
        self.yasuhiko_fc_frame.setFont(font)
        self.yasuhiko_fc_frame.setStyleSheet("color: rgb(255, 255, 255);")
        self.yasuhiko_fc_frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.yasuhiko_fc_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.yasuhiko_fc_frame.setLineWidth(10)
        self.yasuhiko_fc_frame.setMidLineWidth(10)
        self.yasuhiko_fc_frame.setObjectName("yasuhiko_fc_frame")
        self.yasuhiko_fc_table = QtWidgets.QTableView(self.yasuhiko_fc_frame)
        self.yasuhiko_fc_table.setGeometry(QtCore.QRect(10, 10, 771, 101))
        self.yasuhiko_fc_table.setObjectName("yasuhiko_fc_table")
        self.yasuhiko_vol_frame = QtWidgets.QFrame(self.takao_frame_2)
        self.yasuhiko_vol_frame.setGeometry(QtCore.QRect(10, 530, 791, 351))
        font = QtGui.QFont()
        font.setPixelSize(29)
        self.yasuhiko_vol_frame.setFont(font)
        self.yasuhiko_vol_frame.setStyleSheet("color: rgb(255, 255, 255);")
        self.yasuhiko_vol_frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.yasuhiko_vol_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.yasuhiko_vol_frame.setLineWidth(10)
        self.yasuhiko_vol_frame.setMidLineWidth(10)
        self.yasuhiko_vol_frame.setObjectName("yasuhiko_vol_frame")
        self.yasuhiko_vol_chart = QtWidgets.QGridLayout(self.yasuhiko_vol_frame)
        self.yasuhiko_vol_chart.setGeometry(QtCore.QRect(10, 10, 771, 331))
        self.yasuhiko_vol_chart.setObjectName("yasuhiko_vol_chart")
        self.yasuhiko_ns_frame = QtWidgets.QFrame(self.takao_frame_2)
        self.yasuhiko_ns_frame.setGeometry(QtCore.QRect(830, 170, 791, 351))
        font = QtGui.QFont()
        font.setPixelSize(29)
        self.yasuhiko_ns_frame.setFont(font)
        self.yasuhiko_ns_frame.setStyleSheet("color: rgb(255, 255, 255);")
        self.yasuhiko_ns_frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.yasuhiko_ns_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.yasuhiko_ns_frame.setLineWidth(10)
        self.yasuhiko_ns_frame.setMidLineWidth(10)
        self.yasuhiko_ns_frame.setObjectName("yasuhiko_ns_frame")
        self.yasuhiko_ns_chart = QtWidgets.QGridLayout(self.yasuhiko_ns_frame)
        self.yasuhiko_ns_chart.setGeometry(QtCore.QRect(10, 10, 771, 331))
        self.yasuhiko_ns_chart.setObjectName("yasuhiko_ns_chart")
        self.yasuhiko_customers_frame = QtWidgets.QFrame(self.takao_frame_2)
        self.yasuhiko_customers_frame.setGeometry(QtCore.QRect(830, 530, 791, 351))
        font = QtGui.QFont()
        font.setPixelSize(29)
        self.yasuhiko_customers_frame.setFont(font)
        self.yasuhiko_customers_frame.setStyleSheet("color: rgb(255, 255, 255);")
        self.yasuhiko_customers_frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.yasuhiko_customers_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.yasuhiko_customers_frame.setLineWidth(10)
        self.yasuhiko_customers_frame.setMidLineWidth(10)
        self.yasuhiko_customers_frame.setObjectName("yasuhiko_customers_frame")
        self.yasuhiko_customers_chart = QtWidgets.QGridLayout(self.yasuhiko_customers_frame)
        self.yasuhiko_customers_chart.setGeometry(QtCore.QRect(10, 10, 771, 331))
        self.yasuhiko_customers_chart.setObjectName("yasuhiko_customers_chart")
        self.yasuhiko_open_frame = QtWidgets.QFrame(self.takao_frame_2)
        self.yasuhiko_open_frame.setGeometry(QtCore.QRect(830, 30, 181, 121))
        font = QtGui.QFont()
        font.setPixelSize(29)
        self.yasuhiko_open_frame.setFont(font)
        self.yasuhiko_open_frame.setStyleSheet("color: rgb(255, 255, 255);")
        self.yasuhiko_open_frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.yasuhiko_open_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.yasuhiko_open_frame.setLineWidth(10)
        self.yasuhiko_open_frame.setMidLineWidth(10)
        self.yasuhiko_open_frame.setObjectName("yasuhiko_open_frame")
        self.yasuhiko_open_label = QtWidgets.QLabel(self.yasuhiko_open_frame)
        self.yasuhiko_open_label.setGeometry(QtCore.QRect(10, 10, 161, 41))
        font = QtGui.QFont()
        font.setPixelSize(20)
        self.yasuhiko_open_label.setFont(font)
        self.yasuhiko_open_label.setObjectName("yasuhiko_open_label")
        self.yasuhiko_open_num_label = QtWidgets.QLabel(self.yasuhiko_open_frame)
        self.yasuhiko_open_num_label.setGeometry(QtCore.QRect(80, 50, 61, 51))
        font = QtGui.QFont()
        font.setPixelSize(39)
        self.yasuhiko_open_num_label.setFont(font)
        self.yasuhiko_open_num_label.setObjectName("yasuhiko_open_num_label")
        self.takao_win_frame_2 = QtWidgets.QFrame(self.takao_frame_2)
        self.takao_win_frame_2.setGeometry(QtCore.QRect(1240, 30, 181, 121))
        font = QtGui.QFont()
        font.setPixelSize(29)
        self.takao_win_frame_2.setFont(font)
        self.takao_win_frame_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.takao_win_frame_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.takao_win_frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.takao_win_frame_2.setLineWidth(10)
        self.takao_win_frame_2.setMidLineWidth(10)
        self.takao_win_frame_2.setObjectName("takao_win_frame_2")
        self.yasuhiko_win_label = QtWidgets.QLabel(self.takao_win_frame_2)
        self.yasuhiko_win_label.setGeometry(QtCore.QRect(30, 10, 131, 41))
        font = QtGui.QFont()
        font.setPixelSize(20)
        self.yasuhiko_win_label.setFont(font)
        self.yasuhiko_win_label.setObjectName("yasuhiko_win_label")
        self.yasuhiko_win_num1_label = QtWidgets.QLabel(self.takao_win_frame_2)
        self.yasuhiko_win_num1_label.setGeometry(QtCore.QRect(30, 50, 61, 21))
        font = QtGui.QFont()
        font.setPixelSize(30)
        self.yasuhiko_win_num1_label.setFont(font)
        self.yasuhiko_win_num1_label.setObjectName("yasuhiko_win_num1_label")
        self.yasuhiko_win_num2_label = QtWidgets.QLabel(self.takao_win_frame_2)
        self.yasuhiko_win_num2_label.setGeometry(QtCore.QRect(30, 80, 61, 21))
        font = QtGui.QFont()
        font.setPixelSize(30)
        self.yasuhiko_win_num2_label.setFont(font)
        self.yasuhiko_win_num2_label.setObjectName("yasuhiko_win_num2_label")
        self.takao_outstanding_frame_2 = QtWidgets.QFrame(self.takao_frame_2)
        self.takao_outstanding_frame_2.setGeometry(QtCore.QRect(1440, 30, 181, 121))
        font = QtGui.QFont()
        font.setPixelSize(29)
        self.takao_outstanding_frame_2.setFont(font)
        self.takao_outstanding_frame_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.takao_outstanding_frame_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.takao_outstanding_frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.takao_outstanding_frame_2.setLineWidth(10)
        self.takao_outstanding_frame_2.setMidLineWidth(10)
        self.takao_outstanding_frame_2.setObjectName("takao_outstanding_frame_2")
        self.yasuhiko_outstanding_label = QtWidgets.QLabel(self.takao_outstanding_frame_2)
        self.yasuhiko_outstanding_label.setGeometry(QtCore.QRect(20, 10, 151, 41))
        font = QtGui.QFont()
        font.setPixelSize(20)
        self.yasuhiko_outstanding_label.setFont(font)
        self.yasuhiko_outstanding_label.setObjectName("yasuhiko_outstanding_label")
        self.yasuhiko_doubts_label = QtWidgets.QLabel(self.takao_outstanding_frame_2)
        self.yasuhiko_doubts_label.setGeometry(QtCore.QRect(10, 50, 101, 21))
        font = QtGui.QFont()
        font.setPixelSize(12)
        self.yasuhiko_doubts_label.setFont(font)
        self.yasuhiko_doubts_label.setObjectName("yasuhiko_doubts_label")
        self.yasuhiko_uncommented_label = QtWidgets.QLabel(self.takao_outstanding_frame_2)
        self.yasuhiko_uncommented_label.setGeometry(QtCore.QRect(10, 90, 101, 21))
        font = QtGui.QFont()
        font.setPixelSize(12)
        self.yasuhiko_uncommented_label.setFont(font)
        self.yasuhiko_uncommented_label.setObjectName("yasuhiko_uncommented_label")
        self.line_4 = QtWidgets.QFrame(self.takao_outstanding_frame_2)
        self.line_4.setGeometry(QtCore.QRect(90, 50, 16, 61))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.yasuhiko_doubts_num1_label = QtWidgets.QLabel(self.takao_outstanding_frame_2)
        self.yasuhiko_doubts_num1_label.setGeometry(QtCore.QRect(100, 50, 61, 21))
        font = QtGui.QFont()
        font.setPixelSize(11)
        self.yasuhiko_doubts_num1_label.setFont(font)
        self.yasuhiko_doubts_num1_label.setObjectName("yasuhiko_doubts_num1_label")
        self.yasuhiko_doubts_num2_label = QtWidgets.QLabel(self.takao_outstanding_frame_2)
        self.yasuhiko_doubts_num2_label.setGeometry(QtCore.QRect(100, 70, 61, 21))
        font = QtGui.QFont()
        font.setPixelSize(11)
        self.yasuhiko_doubts_num2_label.setFont(font)
        self.yasuhiko_doubts_num2_label.setObjectName("yasuhiko_doubts_num2_label")
        self.yasuhiko_uncommented_num_label = QtWidgets.QLabel(self.takao_outstanding_frame_2)
        self.yasuhiko_uncommented_num_label.setGeometry(QtCore.QRect(100, 90, 61, 21))
        font = QtGui.QFont()
        font.setPixelSize(11)
        self.yasuhiko_uncommented_num_label.setFont(font)
        self.yasuhiko_uncommented_num_label.setObjectName("yasuhiko_uncommented_num_label")
        self.yasuhiko_total_frame = QtWidgets.QFrame(self.takao_frame_2)
        self.yasuhiko_total_frame.setGeometry(QtCore.QRect(1040, 30, 181, 121))
        font = QtGui.QFont()
        font.setPixelSize(29)
        self.yasuhiko_total_frame.setFont(font)
        self.yasuhiko_total_frame.setStyleSheet("color: rgb(255, 255, 255);")
        self.yasuhiko_total_frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.yasuhiko_total_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.yasuhiko_total_frame.setLineWidth(10)
        self.yasuhiko_total_frame.setMidLineWidth(10)
        self.yasuhiko_total_frame.setObjectName("yasuhiko_total_frame")
        self.yasuhiko_total_label = QtWidgets.QLabel(self.yasuhiko_total_frame)
        self.yasuhiko_total_label.setGeometry(QtCore.QRect(20, 10, 151, 41))
        font = QtGui.QFont()
        font.setPixelSize(20)
        self.yasuhiko_total_label.setFont(font)
        self.yasuhiko_total_label.setObjectName("yasuhiko_total_label")
        self.yasuhiko_total_num_label = QtWidgets.QLabel(self.yasuhiko_total_frame)
        self.yasuhiko_total_num_label.setGeometry(QtCore.QRect(20, 50, 61, 51))
        font = QtGui.QFont()
        font.setPixelSize(39)
        self.yasuhiko_total_num_label.setFont(font)
        self.yasuhiko_total_num_label.setObjectName("yasuhiko_total_num_label")
        self.tabWidget.addTab(self.tab_5, "")
        self.verticalLayout.addWidget(self.tabWidget)
        FCWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(FCWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1650, 18))
        self.menubar.setObjectName("menubar")
        FCWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(FCWindow)
        self.statusbar.setObjectName("statusbar")
        FCWindow.setStatusBar(self.statusbar)

        self.retranslateUi(FCWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(FCWindow)

    def retranslateUi(self, FCWindow):
        _translate = QtCore.QCoreApplication.translate
        FCWindow.setWindowTitle(_translate("FCWindow", "MainWindow"))
        self.kota_sum_label.setText(_translate("FCWindow", "Kota Takahashi"))
        self.kota_sum_vol_label.setText(_translate("FCWindow", "Total Vol:"))
        self.kota_sum_ns_label.setText(_translate("FCWindow", "Total NS:"))
        self.kota_sum_jm_label.setText(_translate("FCWindow", "Total JM:"))
        self.hiyoshi_sum_label.setText(_translate("FCWindow", "Seiichi Hiyoshi"))
        self.seiichi_sum_vol_label.setText(_translate("FCWindow", "Total Vol:"))
        self.seiichi_sum_ns_label.setText(_translate("FCWindow", "Total NS:"))
        self.seiichi_sum_jm_label.setText(_translate("FCWindow", "Total JM:"))
        self.takao_sum_label.setText(_translate("FCWindow", "Takao Yamamoto"))
        self.takao_sum_vol_label.setText(_translate("FCWindow", "Total Vol:"))
        self.takao_sum_ns_label.setText(_translate("FCWindow", "Total NS:"))
        self.takao_sum_jm_label.setText(_translate("FCWindow", "Total JM:"))
        self.yasuhiko_sum_label.setText(_translate("FCWindow", "Yasuhiko Suzuki"))
        self.yasuhiko_sum_ns_label.setText(_translate("FCWindow", "Total NS:"))
        self.yasuhiko_sum_jm_label.setText(_translate("FCWindow", "Total JM:"))
        self.yasuhiko_sum_vol_label.setText(_translate("FCWindow", "Total Vol:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("FCWindow", "Summary"))
        self.kota_open_label.setText(_translate("FCWindow", "Open Opportunities"))
        self.kota_open_num_label.setText(_translate("FCWindow", "0"))
        self.kota_win_label.setText(_translate("FCWindow", "LTO Winnable"))
        self.kota_win_num1_label.setText(_translate("FCWindow", "0"))
        self.kota_win_num2_label.setText(_translate("FCWindow", "0"))
        self.kota_outstanding_label.setText(_translate("FCWindow", "LTO Outstanding"))
        self.kota_doubts_label.setText(_translate("FCWindow", "Doubts"))
        self.kota_uncommented_label.setText(_translate("FCWindow", "Uncommented"))
        self.kota_doubts_num1_label.setText(_translate("FCWindow", "0"))
        self.kota_doubts_num2_label.setText(_translate("FCWindow", "0"))
        self.kota_uncommented_num_label.setText(_translate("FCWindow", "0"))
        self.kota_total_label.setText(_translate("FCWindow", "LTO Total EURk"))
        self.kota_total_num_label.setText(_translate("FCWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("FCWindow", "Kota Takahashi"))
        self.seiichi_open_label.setText(_translate("FCWindow", "Open Opportunities"))
        self.seiichi_open_num_label.setText(_translate("FCWindow", "0"))
        self.seiichi_win_label.setText(_translate("FCWindow", "LTO Winnable"))
        self.seiichi_win_num1_label.setText(_translate("FCWindow", "0"))
        self.seiichi_win_num2_label.setText(_translate("FCWindow", "0"))
        self.seiichi_outstanding_label.setText(_translate("FCWindow", "LTO Outstanding"))
        self.seiichi_doubts_label.setText(_translate("FCWindow", "Doubts"))
        self.seiichi_uncommented_label.setText(_translate("FCWindow", "Uncommented"))
        self.seiichi_doubts_num1_label.setText(_translate("FCWindow", "0"))
        self.seiichi_doubts_num2_label.setText(_translate("FCWindow", "0"))
        self.seiichi_uncommented_num_label.setText(_translate("FCWindow", "0"))
        self.seiichi_total_label.setText(_translate("FCWindow", "LTO Total EURk"))
        self.seiichi_total_num_label.setText(_translate("FCWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("FCWindow", "Seiichi Hiyoshi"))
        self.takao_open_label.setText(_translate("FCWindow", "Open Opportunities"))
        self.takao_open_num_label.setText(_translate("FCWindow", "0"))
        self.takao_win_label.setText(_translate("FCWindow", "LTO Winnable"))
        self.takao_win_num1_label.setText(_translate("FCWindow", "0"))
        self.takao_win_num2_label.setText(_translate("FCWindow", "0"))
        self.takao_outstanding_label.setText(_translate("FCWindow", "LTO Outstanding"))
        self.takao_doubts_label.setText(_translate("FCWindow", "Doubts"))
        self.takao_uncommented_label.setText(_translate("FCWindow", "Uncommented"))
        self.takao_doubts_num1_label.setText(_translate("FCWindow", "0"))
        self.takao_doubts_num2_label.setText(_translate("FCWindow", "0"))
        self.takao_uncommented_num_label.setText(_translate("FCWindow", "0"))
        self.takao_total_label.setText(_translate("FCWindow", "LTO Total EURk"))
        self.takao_total_num_label.setText(_translate("FCWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("FCWindow", "Takao Yamamoto"))
        self.yasuhiko_open_label.setText(_translate("FCWindow", "Open Opportunities"))
        self.yasuhiko_open_num_label.setText(_translate("FCWindow", "0"))
        self.yasuhiko_win_label.setText(_translate("FCWindow", "LTO Winnable"))
        self.yasuhiko_win_num1_label.setText(_translate("FCWindow", "0"))
        self.yasuhiko_win_num2_label.setText(_translate("FCWindow", "0"))
        self.yasuhiko_outstanding_label.setText(_translate("FCWindow", "LTO Outstanding"))
        self.yasuhiko_doubts_label.setText(_translate("FCWindow", "Doubts"))
        self.yasuhiko_uncommented_label.setText(_translate("FCWindow", "Uncommented"))
        self.yasuhiko_doubts_num1_label.setText(_translate("FCWindow", "0"))
        self.yasuhiko_doubts_num2_label.setText(_translate("FCWindow", "0"))
        self.yasuhiko_uncommented_num_label.setText(_translate("FCWindow", "0"))
        self.yasuhiko_total_label.setText(_translate("FCWindow", "LTO Total EURk"))
        self.yasuhiko_total_num_label.setText(_translate("FCWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("FCWindow", "Yasuhiko Suzuki"))


if __name__ == "__main__":
    import sys
    os.environ["QT_AUTO_SCREEN_SCALE_FACTOR"] = "1"
    app = QtWidgets.QApplication(sys.argv)
    app.setStyle("Fusion")
    FCWindow = QtWidgets.QMainWindow()
    ui = Ui_FCWindow()
    ui.setupUi(FCWindow)
    FCWindow.show()
    sys.exit(app.exec_())
